FORMAT_EDGELIST_FILE_ENDING_REGEX   = '.edgelist.csv$'
FORMAT_CSV_FILE_ENDING_REGEX        = '.csv$'
FORMAT_NT_FILE_ENDING_REGEX         = '.nt$'

SUPPORTED_FORMATS = { 'edgelist' : FORMAT_EDGELIST_FILE_ENDING_REGEX, \
    'csv' : FORMAT_CSV_FILE_ENDING_REGEX, \
    'nt' : FORMAT_NT_FILE_ENDING_REGEX }
